### ISSUE TITLE
Update CFN templates to support us-east-2 (Ohio)

### ISSUE THREAD

**Issue by astrostl** [acantril/aCloudGuru-DynamoDB#1]
Howdy. Ohio isn't supported in your CFN templates. See attached screenshot that was yielded for LabMachine, don't know what others are impacted.
<img width="756" alt="screen shot 2016-10-28 at 4 27 31 pm" src="https://cloud.githubusercontent.com/assets/1126471/19822951/bd504e52-9d2b-11e6-93bd-6351bbc1238c.png">

**Comment by acantril** [comment]
Thanks for submitting and sorry for the delay - looking at this now.

**Comment by acantril** [comment]
Labmachine.json updated with us-east-2
